services:
    - type: web
      name: waziri-cup-backend
      runtime: node
      plan: free
      region: oregon # choose your preferred region
      branch: main
      buildCommand: npm install
      startCommand: npm start
      autoDeploy: true
      envVars:
          - key: NODE_ENV
            value: production
